#!/usr/bin/env bash

executionplane --silent docker volume create hkvb_poc_confluent__connect_secrets_volume
	
executionplane --silent docker volume create hkvb_poc_confluent__connect_connect_secrets_volume
	
executionplane --silent docker volume create hkvb_poc_confluent__connect_data_volume
	
executionplane --silent docker volume create hkvb_poc_confluent__connect_jars_volume
	
executionplane --silent docker volume create hkvb_poc_confluent__kafka_secrets_volume
	
executionplane --silent docker volume create hkvb_poc_confluent__kafka_data_volume
	
executionplane --silent docker volume create hkvb_poc_confluent__ksqldb_queries_volume
	
executionplane --silent docker volume create hkvb_poc_confluent__schema_registry_secrets_volume
	
executionplane --silent docker volume create hkvb_poc_confluent__zookeeper_secrets_volume
	
executionplane --silent docker volume create hkvb_poc_confluent__zookeeper_data_volume
	
executionplane --silent docker volume create hkvb_poc_confluent__zookeeper_log_volume
	

executionplane --silent docker run -v vcw_infometis_repos:/source -v hkvb_poc_confluent__kafka_data_volume:/var/lib/kafka/data ${VCW_REGISTRY}hkvb/infometis console cmd cp -r /source/hkvb/poc/confluent/./_solution/_configuration/volumes/kafka_data_volume/* /var/lib/kafka/data

