#!/usr/bin/env bash

executionplane --silent docker volume create hkvb_poc_elastickafka__elastic_volume
	
executionplane --silent docker volume create hkvb_poc_elastickafka__grafana_volume
	
executionplane --silent docker volume create hkvb_poc_elastickafka__kafka_secrets_volume
	
executionplane --silent docker volume create hkvb_poc_elastickafka__kafka_data_volume
	
executionplane --silent docker volume create hkvb_poc_elastickafka__ksqldb_queries_volume
	
executionplane --silent docker volume create hkvb_poc_elastickafka__schema_registry_secrets_volume
	
executionplane --silent docker volume create hkvb_poc_elastickafka__streamsets_volume
	
executionplane --silent docker volume create hkvb_poc_elastickafka__zookeeper_secrets_volume
	
executionplane --silent docker volume create hkvb_poc_elastickafka__zookeeper_data_volume
	
executionplane --silent docker volume create hkvb_poc_elastickafka__zookeeper_log_volume
	
