FROM ${VCW_REGISTRY}hkvb/bash.wrapper:5.0.18

COPY ./ /vcw/repo/

LABEL co.vcweb.schema-version="1.0" \
      co.vcweb.label="New InfoMetis Repo" \
      co.vcweb.description="A new InfoMetis repository." \
      co.vcweb.realm="khvb" \
      co.vcweb.image="poc" \
      co.vcweb.tag="1.0.0}" \
      co.vcweb.maintainer="infometis@vcweb.co"
