#!/usr/bin/env bash

executionplane --silent docker container prune --force
continue="true"
while [[ "true" == "$continue" ]] ;
do
	executionplane docker volume rm "hkvb_poc_blank_solution__blank_volume"
	result=$(docker volume ls | grep "hkvb_poc_blank_solution__blank_volume")
	if [[ "$result" == "" ]] ; then
		continue="false"
	else
		sleep 3;
	fi
done;
	
